---
sudo: false
language: php
dist: trusty
matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
      env:
        - RUN_LINTER=1
        - RUN_SNYK=1
    - php: nightly
  allow_failures:
    - php: nightly
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - composer install --no-interaction
  - phpenv rehash
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; npm install -g snyk; fi"
install:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"
script:
  - mkdir -p build/logs
  - "if [[ $RUN_LINTER ]]; then vendor/bin/php-cs-fixer fix --verbose --diff --dry-run --config=.php_cs; fi"
  - "if [[ $RUN_LINTER ]]; then vendor/bin/phpcs --standard=PSR2 src/; fi"
  - ./vendor/bin/phpunit
after_success:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then snyk monitor --org=maxmind --project-name=maxmind/web-service-common-php; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "UW1TFSQDZGymtfapzAZcCyl67UOdeZKHfQ6L2XD8vK8+CPEAfJ1vXlaweoKTiGyvkfYGRa/nFBudvK+XQ81l1mQ1LIo0VBSGYpd/XMJ8H1fMn3lQLGni1INKn7tViKXpo3mzxyoTwf1fQoqCbBtzVcH/6tpgtqj1HCsvzgs8jMIV6EkRTXDTdY2y0o6XTkNwqGhByikrtj/BKh55ifAKFQYp4/VLGQC8+cEugefWQaaIWiuF4fy08ta94w/eIsg1i2+tVWTbH1G60ZHRbjKb0ERAbjOFRSC3qHmie2fnklARbNp9yo/O+GCSkJxF63cwHTN7xnDGx7VLNxOma7gEHBZx0zfO+2PAjnqwImfopdWcuPpB4oKvZXWEoaNdKQPRkeMyWR29uy0xtd49IpuuJwJgyrD+rWlRhJTWbM30FSuCBN2To3Vj17r5cL03d/iJXrfpECdEYhybTa2dzXvs2jHaFuwONSi5Mn8z6x2++v1JYwO5ZtAShpEBlWJXze9HGfPGYzF/HcD5gF8Cw0SuQKPKWQU3IWS0MxlLo9nJ4K0OIJKh2Yg5xftgw6YLDhuc4QuBq0OJLRVWl2p97yRxYLRBubbLFZ53GCUe7yzUoSzs/7CtswVKAmeg8USJZdfRD5mkt/1g9BxCW5ivrDnm90h58z8IgM5WguJ77mR+HZs=\n"
env:
  global:
    secure: "wvc3RIt6/2lpi/Nx2r949pc0t4i/Js6uCw9TpMA8NqticLUTbzV0up0zBqFfubtEfOOA0jJwDykYW91Jl2E4/qccsBIdYGu+0Xp10YAPr1/1LFe8No6f+IDnBcjr5P0bMW7jZjjgBh2pkw3hf2Z/buHJ691zIBXU0jlAfjo7i/a0qc4PEGGpFt8m1FRmEUCp/dcEQ2bCwVsEjL4Jo2KbWr9U5UfQH0SUqFSFDJMTos02jY/rUUnBeoTF+5WqnlJICTg9Q4uAvIdkkq7RRh9QwgrDVcUr0R4h6FVDkmo9SGzSiYzKU7laji0YQ6leV3De/j3QwQrDrkkUkJ/zVbqINJ7BcRk3kSovEjdk6aFQdpFXt8p4JE1p8wepgKW6VZ4+JwsHnv66bbT7BJwCW8Z/Ja0KlqYr80I7ujedu/YW2pgZXXrTy2kEP7xBTKgR2+KpyfSkVxamOkcN62WosPww0GgWpYFogtuhpgmgOCz7ryZfZGsHNsoXXyizFsEoDizSOvQW7XRcpvM0Ga0sWMhe1miRhtAWULOvhQZUVQ6Jo1CL7VOHcFN3jY74ZhU794XwTFX0bYPp25kyErXdnq+URlTKP1wnxNz0Yaz0BsPzf+Q/qoDElhfdHe+PQSYni2uy7i1evIxTMivmrTDw7/5FiNG+HZVeZnqLD4AaBljHdpU="
